### ISSUE TITLE
Отсутствует переход в меню "Роли" в кейсах 3. Удаление созданной роли и 4. Изменение роли, изменение поля Имя роли

### ISSUE THREAD

**Issue by PycJIaH** [Ceredira/CerediraTess_Test#32]
Тестовое окружение
Браузер - Версия 101.0.4951.54 (Официальная сборка), (64 бит)
ОС - Windows 10, 64 бит.

Заголовок: Отсутствует переход в меню "Роли" в кейсах 3. Удаление созданной роли и 4. Изменение роли, изменение поля Имя роли

Шаги для воспроизведения:

[Войти на сайт с пользователем "admin"](https://github.com/Ceredira/CerediraTess_Test/blob/master/1.%20%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/0.%20%D0%A8%D0%B0%D0%B3%D0%B8/1.%20%D0%92%D0%BE%D0%B9%D1%82%D0%B8%20%D0%BD%D0%B0%20%D1%81%D0%B0%D0%B9%D1%82%20%D1%81%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%BC%20username.md)
[Создать роль "tester_4_1"](https://github.com/Ceredira/CerediraTess_Test/blob/master/1.%20%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/0.%20%D0%A8%D0%B0%D0%B3%D0%B8/4.%20%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C%20%D1%80%D0%BE%D0%BB%D1%8C%20%D1%81%20%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BC%20userrole.md)
Фактический результат:
Отсутствует переход в раздел "Администрирование -> Роли"

Ожидаемый результат:
Присутствует окно ролей

**Comment by ping335** [comment]
- В кейсе  [3. Удаление созданной роли](https://github.com/Ceredira/CerediraTess_Test/blob/master/1.%20%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/1.%20%D0%92%D0%B5%D0%B1-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81/3.%20%D0%92%D1%81%D0%BF%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB/%D0%90%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5/%D0%A0%D0%BE%D0%BB%D0%B8/3.%20%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%BD%D0%BE%D0%B9%20%D1%80%D0%BE%D0%BB%D0%B8.md) - переход происходит при выполнении шага 2. 
- В кейсе 4 - аналогично

Ошибки нет.
