### ISSUE TITLE
Перепутаны пункты 6 и 7 в меню "Роли" в кейсе 10. Дублирование записи роли, негативный сценарий

### ISSUE THREAD

**Issue by PycJIaH** [Ceredira/CerediraTess_Test#33]
Тестовое окружение
Браузер - Версия 101.0.4951.54 (Официальная сборка), (64 бит)
ОС - Windows 10, 64 бит.

Шаги для воспроизведения:
1. [Войти на сайт с пользователем "admin"](https://github.com/Ceredira/CerediraTess_Test/blob/master/1.%20%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/0.%20%D0%A8%D0%B0%D0%B3%D0%B8/1.%20%D0%92%D0%BE%D0%B9%D1%82%D0%B8%20%D0%BD%D0%B0%20%D1%81%D0%B0%D0%B9%D1%82%20%D1%81%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B5%D0%BC%20username.md)
2. В главном меню перейти в раздел "Администрирование -> Роли"
3. Нажать на иконку "Дублировать запись" роли с названием "admin"
4. Ввести в поле "Название роли" значение "admin"
5. Нажать на кнопку "Сохранить"
6. Дубликат роли "admin" не создался

Фактический результат:
Под основным меню появилось сообщение "Ошибка целостности."

Ожидаемый результат:
Дубликат роли "admin" не создался

Примечание:
Более корректно было бы:
5. Нажать на кнопку "Сохранить"
6. Под основным меню появилось сообщение "Ошибка целостности."
7. Перейти во вкладку "Список"
8. В таблице "Список" не отображается дважды строка со значением "admin" в столбце "Название роли"

**Comment by ping335** [comment]
[Исправила ](https://github.com/Ceredira/CerediraTess_Test/pull/35)
